import mongoose from "mongoose";

const DearProducts = mongoose.model(
  "DearProducts",
  new mongoose.Schema(
    {
      id: String,
      sku: String,
      name: String,
      category: String,
      brand: String,
      type: String,
      costingMethod: String,
      dropShipMode: String,
      defaultLocation: String,
      length: Number,
      width: Number,
      height: Number,
      weight: Number,
      uom: String,
      weightUnits: String,
      dimensionsUnits: String,
      barcode: String,
      minimumBeforeReorder: Number,
      reorderQuantity: Number,
      priceTier1: Number,
      priceTier2: Number,
      priceTier3: Number,
      priceTier4: Number,
      priceTier5: Number,
      priceTier6: Number,
      priceTier7: Number,
      priceTier8: Number,
      priceTier9: Number,
      priceTier10: Number,
      priceTiers: { low: Number, lowMid: Number, mid: Number, midHigh: Number, high: Number, flatRate: Number },
      averageCost: Number,
      shortDescription: String,
      internalNote: String,
      description: String,
      additionalAttribute1: String,
      additionalAttribute2: String,
      additionalAttribute3: String,
      additionalAttribute4: String,
      additionalAttribute5: String,
      additionalAttribute6: String,
      additionalAttribute7: String,
      additionalAttribute8: String,
      additionalAttribute9: String,
      additionalAttribute10: String,
      attributeSet: String,
      discountRule: String,
      tags: String,
      status: String,
      stockLocator: String,
      cogsAccount: String,
      revenueAccount: String,
      expenseAccount: String,
      inventoryAccount: String,
      purchaseTaxRule: String,
      saleTaxRule: String,
      lastModifiedOn: String,
      sellable: Boolean,
      pickZones: String,
      billOfMaterial: Boolean,
      autoAssembly: Boolean,
      autoDisassembly: Boolean,
      quantityToProduce: Number,
      alwaysShowQuantity: Number,
      assemblyInstructionURL: String,
      assemblyCostEstimationMethod: String,
      suppliers: [],
      reorderLevels: [],
      billOfMaterialsProducts: [],
      billOfMaterialsServices: [],
      movements: [],
      attachments: [],
      bomType: String,
      warrantyName: String,
      customPrices: [],
      cartonHeight: Number,
      cartonWidth: Number,
      cartonLength: Number,
      cartonQuantity: Number,
      cartonInnerQuantity: Number,
    },
    { versionKey: false }
  ),
  "DearProducts"
);

export default DearProducts;
