export interface HSNOrder {
  "VB Number": string;
  Requestor: string;
  "Order Print Time": string;
  "PO Number": string;
  "PO Date": number;
  "Import Date": string;
  "Import Age": string;
  "Supplier Product Code": string;
  "Supplier Product Description": string;
  "Partner SKU": string;
  "Requestor Product Description": string;
  QTY: number;
  "Supplier Unit Sell": number;
  "Supplier Pick Group": string;
  "Consumer Ship To Name": string;
  "Consumer Ship To Address 1": string;
  "Consumer Ship To Address 2": string;
  "Consumer Ship To City": string;
  "Consumer Ship To State": string;
  "Consumer Ship To Zip": string;
  "Consumer Ship To Phone": string;
  "Consumer Pers Msg 1": string;
  "Consumer Pers Msg 2": string;
  "Consumer Pers Msg 3": string;
  "Consumer Pers Msg 4": string;
  "Cancel After Date": string;
  "Requested Delivery By": string;
  "Requested Delivery Date": string;
  "Requested Ship Date": string;
  UPC: string;
  "Order Type": string;
  "Line Number": string;
  "POLine Number": string;
  PromotionCode: string;
}
