import mongoose from "mongoose";

const WalmartOrderItemLine = new mongoose.Schema({
  line_item_number: String,
  quantity: String,
  unit_or_basis_for_measurement: String,
  unit_price: String,
  basis_of_unit_price: String,
  buyers_item_number: String,
  ucc: String,
  vendors_sellers_item_number: String,
  buyers_size_code: String,
  gtin: String,
  pack: String,
  inner_pack: String,
  line_item_total: String,
});

const WalmartSACItemLine = new mongoose.Schema({
  allowance_or_charge_indicator: String,
  service_promotion_allowance_or_charge: String,
  amount: String,
  allowance_charge_percent_qualifier: String,
  percent_decimal_format: String,
  allowance_or_charge_method_of_handling: String,
});

const WalmartOrders = mongoose.model(
  "walmart_orders",
  new mongoose.Schema(
    {
      purchase_order_number: String,
      purchase_order_date: String,
      asn: String,
      bol_check_digit: String,
      bol_with_check_digit: String,
      bol_without_check_digit: String,
      mabd: String,
      actual_weight: String,
      carrier_SCAC: String,
      carrier_reference: String,
      buying_party_purchaser: String,
      ship_to_street: String,
      ship_to_city: String,
      ship_to_country: String,
      cube: String,
      h: String,
      w: String,
      l: String,
      class: String,
      nmfc: String,
      currency: String,
      department_number: String,
      description: String,
      do_not_deliver_after: String,
      extended_reference_information: String,
      floor_or_pallet: String,
      global_location_number: String,
      gross_value: String,
      internal_vendor_number: String,
      invoice_amount: String,
      invoice_date: String,
      invoicing: String,
      load_destination: String,
      load_id: String,
      location_qualifier: String,
      merchandise_type_code: String,
      note: String,
      number_of_case: String,
      number_of_line_items: String,
      picklist: String,
      po_destination_dc_number: String,
      postal_code: String,
      promotion_deal_number: String,
      purchase_order_type: String,
      sale_order_number: String,
      ship_mabd: String,
      ship_po_date: String,
      ship_date_scheduled: String,
      ship_no_later: String,
      ship_not_before: String,
      shipment_method_of_payment: String,
      state_or_province: String,
      supplier_manufacturer: String,
      terms_basis: String,
      terms_discount_days_due: String,
      terms_discount_percent: String,
      terms_net_days: String,
      terms_type_code: String,
      ticket_number: String,
      transaction_set_purpose: String,
      order_line_item: [WalmartOrderItemLine],
      sac_line_item: [WalmartSACItemLine],
    },
    { versionKey: false }
  ),
  "walmart_orders"
);

export default WalmartOrders;
